server:
  port: 9999

app:
  feign:
    client:
      config:
        cloud:
          url: "http://localhost:9997"
        reference:
          url: "http://localhost:9998"

logging:
  level:
    dev.zig.controller.StudentController: DEBUG