server:
  port: 9998
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rtk
    username: postgres
    password: postgres
    testWhileIdle: true
    test-on-borrow: true
    hikari:
      maxLifetime: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    dev.zig.controller.StudentController: DEBUG

feign:
  client:
    config:
      print:
        url: http://localhost:8089
