server:
  port: 9998

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    testWhileIdle: true
    test-on-borrow: true
    hikari:
      maxLifetime: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
  liquibase:
    change-log: db/changelog/changelog-master.yaml

file:
  storage:
    location: cloud.src.main.resources.documents


logging:
  level:
    dev.zig.controller.StudentController: DEBUG

