CREATE TABLE clients
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(255) CHECK ( first_name <> '' ) NOT NULL,
    last_name  VARCHAR(255) CHECK ( last_name <> '' )  NOT NULL,
    patronymic VARCHAR(255) CHECK ( patronymic <> '' ) NOT NULL
);
