CREATE TABLE accounts
(
    account_id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id        BIGINT REFERENCES clients (client_id) NOT NULL,
    account_number   INT UNIQUE                            NOT NULL,
    account_currency VARCHAR                               NOT NULL
);

CREATE INDEX account_number_index ON accounts (account_number);
