CREATE TABLE operations
(
    id             INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp      TIMESTAMP                   NOT NULL,
    payment_method VARCHAR                     NOT NULL,
    sum            BIGINT                      NOT NULL
);
