server:
  port: 9998

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    locations: classpath:db/migration

logging:
  level:
    dev.zig.controller.StudentController: DEBUG

