DROP TABLE IF EXISTS contracts;
DROP TABLE IF EXISTS operations;
DROP TABLE IF EXISTS payment_methods;
DROP INDEX IF EXISTS account_number_index;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS currencies;
DROP TABLE IF EXISTS clients;

CREATE TABLE clients
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(255) CHECK ( first_name <> '' ) NOT NULL,
    last_name  VARCHAR(255) CHECK ( last_name <> '' )  NOT NULL,
    patronymic VARCHAR(255) CHECK ( patronymic <> '' ) NOT NULL
);

CREATE TABLE currencies
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR CHECK ( name <> '' ) NOT NULL
);

CREATE TABLE accounts
(
    id                  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id           INT REFERENCES clients (id)    NOT NULL,
    account_number      INT UNIQUE                     NOT NULL,
    account_currency_id INT REFERENCES currencies (id) NOT NULL
);

CREATE INDEX account_number_index ON accounts (account_number);

CREATE TABLE payment_methods
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR CHECK ( name <> '' ) NOT NULL
);

CREATE TABLE operations
(
    id                INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp         TIMESTAMP                           NOT NULL,
    payment_method_id INT REFERENCES payment_methods (id) NOT NULL,
    sum               INT                                 NOT NULL
);

CREATE TABLE contracts
(
    id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contract_number INT UNIQUE                  NOT NULL,
    contract_date   DATE                        NOT NULL,
    client_id       INT REFERENCES clients (id) NOT NULL
);
